### PR TITLE
fix error 'content.forEach is not a function' in getSymbol

### PR DESCRIPTION
**Pull request by twhtanghk**
npm test passed. Please review the minor fix.

### CODE REVIEW

**Comment by phamleduy04** [comment]
Thank you for sending a PR. I will take a look of it!

**Comment by phamleduy04** [comment]
LGTM! Thanks again for fixing bugs!

**Comment by phamleduy04** [comment]
@all-contributors please add @twhtanghk for code and bug

**Comment by will-tb** [comment]
@phamleduy04 when will this fix be available in npm?

**Comment by phamleduy04** [comment]
I will push it ASAP.

**Comment by will-tb** [comment]
Thank you.

**Comment by phamleduy04** [comment]
You can install the latest version of this package by `npm i yahoo-stock-api@latest` @will-tb

**Pull request merged**
